### ISSUE TITLE
6- save data and code in tables

### ISSUE THREAD

**Issue by Wazzaps** [Wazzaps/MMN14#6]

**Comment by GititKurbet** [comment]
1) אני צריכה לבדוק אם שם תוית חוקי
2) להכניס פקודות לטבלה המתאימה
3) לכל אחד מdirective ..  יש פונקציה (לכל פקודה - רק לפקודות לאסמבלר שמתחילות בנקודה) 
4) בstruct לעדכן את ה DTAT לעדכן עם REALLOC זה בעצם כל המידע שיכנס בזכרון
